### ISSUE TITLE
No Button and error at deactivating

### ISSUE THREAD

**Issue by JPRuehmann** [Garoe/ThunderKeepPlus#1]
Hello

I wont get a Button and if I deactivate the AddOn I get the following Error.
onUnload: TypeError: this.tabsArray is null
I´m using Thunderbird 45.4.0 and Kubuntu 16.04 LTS

Thanks,

**Comment by Gara-Dorta** [comment]
Hey,

Thanks for reporting the bug. 
Could you please test again with the dev branch?
I've added an zip, to make it easier to install, just rename it to xpi

[ThunderkeepPlus-0.9.1-dev-tb.zip](https://github.com/Garoe/ThunderKeepPlus/files/596204/ThunderkeepPlus-0.9.1-dev-tb.zip)

**Comment by JPRuehmann** [comment]
Hello
Tried it out, but the only change is that it won´t throw an error at disabling anymore.
There is still no Button.
By the Way whats the difference to thunderkeep, which works perfectly?
Thanks,

**Comment by Gara-Dorta** [comment]
Thanks for testing. I'm still unable to reproduce the error, so I'll try on Kubuntu.
The original Thunderkeep was not creating the button in the latest thunderbird versions, I've also updated the code to be bootstraped which allows for restartless addons and it also tries to switch to the new tab rather than opening a new one

**Comment by Gara-Dorta** [comment]
I'm sorry but I'm still unable to reproduce the issue.
Could you give me a list of the addons that you have installed?
It would also be worth mentioning if you have customized thunderbird in any way.

**Comment by JPRuehmann** [comment]
Hello
Here is the List of my Add-Ons

.vcs Support	0.6.4	true	{efcbec50-6821-11db-bd13-0800200c9a66}
Adblock Plus	2.8.1	true	{d10d0bf8-f5b5-c8b4-a8b2-2b9879e08c5d}
Add-on Compatibility Reporter	1.1.1-signed.1-signed	true	compatibility@addons.mozilla.org
AddressBookTab	1.5	true	AddressBookTab@dischert.luc
All Menus Button	1.1.3.1-signed	true	tb-all-menus-single@codefisher.org
Android Contacts Sync	2.1	true	AndroidContactsSync@rogerang.com
Attach from Clipboard	1.0	true	clipboard@ganss.org
Auto Zoomer	1.0	true	autozoomer@sergem.org
Calendar Tweaks	6.3	true	calendartweaks@DW-dev
Cert Viewer Plus	1.13	true	{cafefdef-5ef8-4222-a8dd-bfd298784eca}
checkCompatibility	1.3.1-signed.1-signed	true	check-compatibility@dactyl.googlecode.com
Clean Links	2.7.1-signed.1-signed	true	{158d7cb3-7039-4a75-8e0b-3bd0a464edd2}
Console²	0.9.1-signed.1-let-fixed.1-signed	true	{1280606b-2510-4fe0-97ef-9b5a22eafe80}
Contacts Sidebar	1.7pre	true	{4dce973c-25a5-4657-8e37-6c2a85c24a7e}
Custom Address Sidebar	1.1	true	asbcustom@gmail.com
CustomizeMyBird	1.0.5	true	CustomizeMyBird@Aris_CTRdev
Display Mail User Agent	1.7.0	true	{F8147CF4-B9E3-445B-AA87-081ED66548F8}
DOM Inspector	2.0.16.1-signed	true	inspector@mozilla.org
Element Hiding Helper für Adblock Plus	1.3.10	true	elemhidehelper@adblockplus.org
Enigmail	1.9.6.1	true	{847b3a00-7ab1-11d4-8f02-006008948af5}
FireTray	0.6.1	true	{9533f794-00b4-4354-aa15-c2bbda6989f8}
FlashGot	1.5.6.13	true	{19503e42-ca3c-4c27-b1e2-9cdb2170ee34}
Folder Pane View Switcher	1.11	true	FolderPaneSwitcher@kamens.us
Forward	0.19	true	forward@mozdev.org
Free Memory Button	1.1.2.1-signed	true	tb-free-memory-single@codefisher.org
Free/Busy	2.0	true	freebusy-thunderbird@d-wise.com
Google+ Tab	1.0	true	google-plus-tab@michael.grafl
ImportExportTools	3.2.4.1	true	{3ed8cc52-86fc-4613-9026-c1ef969da4c3}
Lightning	4.7.5	true	{e2fda1a4-762b-4020-b5ad-a41df1933103}
Lightning Month Tabs	1.9	true	lightningmonthtabs@jlx.84
LightningButton	1.5.4	true	lightningbutton@rsjtdrjgfuzkfg.com
LookOut	1.2.13	true	lookout@aron.rubin
Mnenhy	0.8.6.1-signed.1-let-fixed.1-signed	true	{bf591015-b599-4125-9428-3cb746ddca31}
MoreFunctionsForAddressBook	0.7.5	true	{3e17310d-82e8-4a43-bd2f-7c3055bfe589}
NewScrollbars (aka NoiaScrollbars)	1.2.7	true	NoiaScrollbars@ArisT2_Noia4dev
Password Exporter New 2014	2.0.4	true	{B17C1C5A-04B1-11DB-9804-B622A1EF2014}
PrintingTools	1.2.5	true	{5e9999c2-ba1d-44b6-bcee-5b30ce37d3b0}
Provider für Google Kalender	3.1	true	{a62ef8ec-5fdc-40c2-873c-223b8a6925cc}
QR-Code Add-on für Lightning	1.2.5	true	lightning-qrcode@harald.judt
QuickFolders	4.5	true	quickfolders@curious.be
QuoteCollapse	0.9	true	{0b62b504-857c-4f62-a336-2e8425bd5738}
Reply As Original Recipient	1.0	true	replyasoriginalrecipient@qiqitori.com
Reply To All Reminder	1.0	true	replytoallreminder@qiqitori.com
Rspamd-spamness	0.8.0	true	rspamd-spamness@alexander.moisseev
S3.Google Translator	5.26	true	s3google@translator
Saved Password Editor	2.10.1	true	savedpasswordeditor@daniel.dawson
Scan'Mail	2.1.2	true	scanmail@nassim.kacha
Signature Switch	1.6.14	true	{2ab1b709-ba03-4361-abf9-c50b964ff75d}
THUNDER!Box	0.9.1	true	thunderbox@sourceforge.net
ThunderBrowse	3.82	true	ThunderBrowse@thunderbrowse.com
ThunderKeep	0.6	true	thunderkeep@jensheuschkel.de
URL Link	2.04.3.1-signed.1-signed	true	{139a120b-c2ea-41d2-bf70-542d9f063dfd}
AddExpandedList	1.0.3	false	{beefcf4b-214d-4758-aeaf-96a7d84d7de2}
Always HTML	1	false	alwayshtml@arivald.com
Chromatasks	1.5	false	{25cf5f06-b211-4df3-9d5a-c0ab253a5561}
Clean Subject	0.4.3	false	cleansubject@style-biz.de
Einfache Wochenansicht	1.1	false	simpleweek-view@mozilla.kewis.ch
Exchange 2007/2010 Calendar and Tasks Provider	1.8.5	false	exchangecalendar@extensions.1st-setup.nl
Folderpane Tools	0.6.1	false	{b243fe83-b8a7-47de-855d-21d865243d5d}
Gantt View	1.0.0.4	false	{1510928E-A4FA-43C2-A9AF-99E521B90BC5}
Google Contacts	0.7.13b1	false	{BDD92442-0534-4D6F-A966-BAB7D561D781}
Gravatars	1.1	false	gravatars@tijnschuurmans.nl
Lightweight Themes Manager	0.2.1-signed.1-let-fixed.1-signed	false	lwthemes-manager@loucypher
NestedQuote Remover	0.8.13	false	{12a1584b-2123-473d-8752-e82e74e3cb1b}
New Tab Button	0.1.25	false	{3AB03506-4329-483F-BA03-EA5493232260}
Personas Plus	1.8.0	false	personas@christopher.beard
Provider for Microsoft Exchange	0.18	false	lightning-exchange-provider@gitorious.org
Quote Colors	0.3	false	{B274D460-4DF9-454c-AC69-CA71398D7498}
Signature Fixer	0.3	false	signaturefixer@adan.rehtla
Theme Font & Size Changer	49.6	false	{f69e22c7-bc50-414a-9269-0f5c344cd94c}
Themes Menu	1.24	false	{84625510-7e5d-11e0-a411-0800200c9a66}
ThunderKeepPlus	0.9.1	false	thunderkeepplus@gmail.com
ThunderStats	1.2.2	false	thunderstats@micz.it
WebApp Tabs	2.1	false	webapptabs@fractalbrew.com
Year View	0.4.5	false	yearview@kirgroup.com
Zoiper Communicator	1.01	false	support@zoiper.com
Zoom Button for Thunderbird	0.0.8	false	ZoomButton@accessfirefox.org

Sorry for the Long List.
rather than the installed Add-ons there are no changes in Thunderbird.
Thanks

**Comment by Gara-Dorta** [comment]
After installing all the add-ons I'm still unable to reproduce the issue. 
I've added a few more checks,  which should give me some more information.
Would you mind trying again?
This version also has debugging messages enabled, which should show on the console with the prefix ThunderKeepPlus
[ThunderkeepPlus-0.9.1-dev-tb.zip](https://github.com/Garoe/ThunderKeepPlus/files/610281/ThunderkeepPlus-0.9.1-dev-tb.zip)

**Comment by JPRuehmann** [comment]
Hello
I get 2 Errors on the Screen when starting the Plugin.
-overlayNode: missing Address Book button
-onLoad: TypeError: customButton is null
On the Console I get only messages, no Errors and no Warnings.
After Emptying and stopping/starting the Plugin I get the following.
-ThunderKeepPlus: TKPManager onUnLoad
-ThunderKeepPlus: TKPManager onUnLoad, loaded is false
-Could not read chrome manifest 'file:///opt/thunderbird/chrome.manifest'.
-Warning: attempting to write 14424 bytes to preference extensions.xpiState. This is bad for general -performance and memory usage. Such an amount of data should rather be written to an external file.
-ThunderKeepPlus: TKPManager onLoad
-Warning: attempting to write 14423 bytes to preference extensions.xpiState. This is bad for general -performance and memory usage. Such an amount of data should rather be written to an external file.
That is all I can get.
Thanks,

**Comment by Koekelbe** [comment]
Hello Gents,
I just installed ThunderkeepPlus as well and I encountered the same issues. (no button and error when deactivating).

After trying the debug version I get the same 2 errors as JPRuehmann mentioned upon startup.

On the console I get the following:
-ThunderKeepPlus: TKPManager onUnLoad
-ThunderKeepPlus: TKPManager onUnLoad, loaded is false
-Could not read chrome manifest 'file:///C:/Program%20Files%20(x86)/Mozilla%20Thunderbird/chrome.manifest'.
-Could not read chrome manifest 'jar:file:///C:/Program%20Files%20(x86)/Mozilla%20Thunderbird/extensions/%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D.xpi!/chrome.manifest'.
-ThunderKeepPlus: TKPManager onLoad

No warnings here.
All add-ons were deactivated during this test.

**Comment by Gara-Dorta** [comment]
I'm still unable to reproduce so I'm kind of trying things at random.

The code assumed that the first window that is opened is the right one to add the button, I've rewritten the logic to try on all windows and keep trying on new ones if needed. It might also be useful to set ```extensions.logging.enabled = true``` in ```about:config```, it's used to output more detailed information on addon management.

[ThunderkeepPlus-0.9.1-dev-tb.zip](https://github.com/Garoe/ThunderKeepPlus/files/614011/ThunderkeepPlus-0.9.1-dev-tb.zip)

I also noticed that there is a bug in 0.9 version which causes the code to not to refresh. Just in case, could you disable/enable the addon a few times after installation to make sure that it refreshes properly?

**Comment by JPRuehmann** [comment]
Hello
at least there are no errormessages anymore
But there is still no Button.
Here is the logging.

1480152267891	DeferredSave.extensions.json	DEBUG	Save changes
1480152267894	addons.xpi-utils	DEBUG	Updating active state for add-on thunderkeepplus@gmail.com to true
1480152267895	DeferredSave.extensions.json	DEBUG	Save changes
1480152267895	addons.xpi	DEBUG	Registering manifest for /home/ruehmann/.thunderbird/mnpyy66l.default/extensions/thunderkeepplus@gmail.com.xpi
1480152267896	addons.xpi	DEBUG	Loading bootstrap scope from /home/ruehmann/.thunderbird/mnpyy66l.default/extensions/thunderkeepplus@gmail.com.xpi
1480152267898	addons.xpi	DEBUG	Calling bootstrap method startup on thunderkeepplus@gmail.com version 0.9.1
ThunderKeepPlus: TKPManager onLoad
ThunderKeepPlus: TKPManager onLoad
1480152267905	addons.xpi	DEBUG	Updating XPIState for {"id":"thunderkeepplus@gmail.com","syncGUID":"X_bi0kLgjJR2","location":"app-profile","version":"0.9.1","type":"extension","internalName":null,"updateURL":null,"updateKey":null,"optionsURL":null,"optionsType":null,"aboutURL":null,"icons":{},"iconURL":"chrome://thunderkeepplus/skin/google_keep_logo_large.png","icon64URL":null,"defaultLocale":{"name":"ThunderKeepPlus","description":"Google Keep for Thunderbird","creator":"Garoe Dorta","homepageURL":"https://github.com/Garoe/ThunderKeepPlus","contributors":["Jens Heuschkel"]},"visible":true,"active":true,"userDisabled":false,"appDisabled":false,"descriptor":"/home/ruehmann/.thunderbird/mnpyy66l.default/extensions/thunderkeepplus@gmail.com.xpi","installDate":1480151407000,"updateDate":1480151407000,"applyBackgroundUpdates":1,"bootstrap":true,"skinnable":false,"size":56535,"sourceURI":"file:///home/ruehmann/Downloads/ThunderkeepPlus-0.9.1-dev-tb.xpi","releaseNotesURI":null,"softDisabled":false,"foreignInstall":false,"hasBinaryComponents":false,"strictCompatibility":false,"locales":[{"locales":["es-ES"],"name":"ThunderKeepPlus","description":"Google Keep en Thunderbird","creator":null,"homepageURL":null},{"locales":["de"],"name":"ThunderKeepPlus","description":"Google Keep für Thunderbird","creator":null,"homepageURL":null}],"targetApplications":[{"id":"{3550f703-e582-4d05-9a08-453d09bdfdc6}","minVersion":"13.0","maxVersion":"45.*"}],"targetPlatforms":[],"multiprocessCompatible":false,"seen":true}
1480152267905	addons.xpi	DEBUG	getModTime: Recursive scan of thunderkeepplus@gmail.com
Warning: attempting to write 14423 bytes to preference extensions.xpiState. This is bad for general performance and memory usage. Such an amount of data should rather be written to an external file.
1480152267909	DeferredSave.extensions.json	DEBUG	Starting timer
1480152268314	DeferredSave.extensions.json	DEBUG	Starting write
1480152268547	DeferredSave.extensions.json	DEBUG	Write succeeded

Thanks,

**Comment by JPRuehmann** [comment]
I´ve restartet it about 50 times no change.

**Comment by Gara-Dorta** [comment]
Thanks for testing it out.

I've done a bit of a workaround. Now it first places the button in the customize toolbar and then tries to put it in the right place. In case of failure, it can now be moved manually and it will remember the new position thereafter. A pop up notifying the failure should appear in that case.

I've also added a few more debug messages.
Also, it should be enough to disable/enable the addon just twice to ensure the caches are cleaned.

[ThunderKeepPlus-0.9.1-dev-tb.zip](https://github.com/Garoe/ThunderKeepPlus/files/614417/ThunderKeepPlus-0.9.1-dev-tb.zip)

**Comment by JPRuehmann** [comment]
Thank you, now it works like a Charm.

**Comment by Gara-Dorta** [comment]
Great to hear that.
Thanks again for the help.
