### ISSUE TITLE
Google Keep button diseapear when closing Thunderbird

### ISSUE THREAD

**Issue by franckgaga** [Garoe/ThunderKeepPlus#11]
Running Thunderbird 68.2.2 on linux mint 19.2 cinnamon.

The Google keep toolbar button disappear when closing and re-opening thunderbird. Disabling and re-enabling the extension make it re-appear.

Thanks for the good work !

**Comment by Gara-Dorta** [comment]
Thanks for getting in touch about this issue.

Could you test if this behaviour continues after doing the steps below?

Right click on the toolbar and select "customise", then drag the button to a different location on the toolbar. Leaving the button on the new location, close and re-open thunderbird.

**Comment by franckgaga** [comment]
It works, this behaviour stops when dragging the button to a different location!
Thanks for the tips !

**Comment by Gara-Dorta** [comment]
That's good to hear. It sounds like it's a variation of #2, which I'm hoping to fix for the next release of thunderbird.
