### ISSUE TITLE
ThunderKeepPlus not compatible with Thunderbird 78.2.2

### ISSUE THREAD

**Issue by marlenejoy** [Garoe/ThunderKeepPlus#14]
My Thunderbird updated and ThunderKeepPlus shows that it's enabled, but no longer shows on a tab. When I go to the Add-Ons search page for Thunderbird (https://addons.thunderbird.net/en-US/thunderbird/search/?q=google%20keep), it says ThunderKeepPlus is not compatible with my version of Thunderbird (which is 78.2.2).

**Comment by Gara-Dorta** [comment]
Hi, thanks for reporting this issue. Unfortunately, the addon is not compatible with Thunderbird 78, so it shouldn't have allowed you to enable it. To make it compatible, #13 needs to be solved but I don't have a ETA on this. To be honest, I'm not using this addon any more, so I don't have a lot of motivation to continue it's development. Still, I plan to to solve this eventually. In any case, if you are particularly keen on using it, I posted a beta version compatible with Thunderbird 78 [here](https://github.com/Garoe/ThunderKeepPlus/issues/12#issuecomment-655565792), which has some drawbacks as described in the comment.

**Comment by marlenejoy** [comment]
Thank you! I installed the beta version that you supplied and, so far, it's working for me. It put a button on my toolbar and I dragged that up so it would open in a new tab.
