### ISSUE TITLE
Message "You have been logged out"

### ISSUE THREAD

**Issue by TH-RBK** [Garoe/ThunderKeepPlus#17]
Hi,

I have the problem, that I could not edit or add any notes anymore. 
I always get the message, that I am logged out an should reload, but reloading does not help.

![Img_2021 06 04_12h25m48s_001_Google Notizen - Mozilla Thunderbird](https://user-images.githubusercontent.com/3983994/120788574-c9392680-c530-11eb-9fb6-6fe9ca30872e.jpg)

The gmail account works without any problem, so it does not seem to be a credential issue.

I have the problem on two computers running on Windows 10 with Thunderbird 78.11.0.
The plugin version is 0.10.8.

Thanks for your help.

Thomas

**Comment by Gara-Dorta** [comment]
Hi there,

I'm sorry to hear that it's not working any more for you. The standard solution to most problems related to the plug in is to delete all cookies. Can you go to tools -> clear recent history, change time range to everything and select cookies and cache to clear, and then open the tab again?

**Comment by TH-RBK** [comment]
Hi Garoe,

thank you for your quick reply. 
It worked on both systems.  
Thanks for your help!!! 🥇 

Thomas
