### ISSUE TITLE
Issue with 91.13.1

### ISSUE THREAD

**Issue by soistheman** [Garoe/ThunderKeepPlus#18]
Since version 91.13.1, Google keep having issue and it keep spinning and won't be able to load the latest notes.  I was able to replicate this issue with 2 PCs with Windows 10 & 11.  Keep still works by downgrading Thunderbird to 91.10.0.

1. Open keep which keep spinning and won't refresh. 
2. Click on account icon on right top and wait for error message "Something went wrong.  Refresh to try again or choose another account."
3. Click on hyperlink on "choose another account"
4. Sign out of Google account.
6. Sign in to Google account.  (I am using 2FA but it won't ask for code, simply typing my password let me log back in.  I think Thunderbird is keeping cache or cookies)
7. Only for the 1st time Keep works.  However after restarting Thunderbird or opening new tab for Keep it will start spinning again.

**Comment by Gara-Dorta** [comment]
I'm afraid this is an upstream thunderbird issue which I have no control over. The only think I can tell you is to delete the cookies and hope that fixes it. 

Go to tools -> clear recent history, change time range to everything and select cookies and cache to clear, and then open the tab again.
