### ISSUE TITLE
Turn on Google Keep reminders? Pop-up Message

### ISSUE THREAD

**Issue by jebear1** [Garoe/ThunderKeepPlus#19]
Is there a way to approve or remove this pop-up message. It appears every time that I open Google Keep Tab. I am using the latest version of Thunderbird on Windows 11. 

![image](https://user-images.githubusercontent.com/130922880/232327946-a836ce32-d184-48ed-a1fb-24cea31b51ee.png)

I think this is a great plugin.
Many thanks.

John

**Comment by Gara-Dorta** [comment]
Hi, thanks for reporting the issue. Unfortunately, I don't have time anymore for add new features or fix issues. I'm only ensuring that the minimal functionality still works as thunderbird updates.
