### ISSUE TITLE
Cannot choose which email account Keep profile is opened

### ISSUE THREAD

**Issue by SirElismyer** [Garoe/ThunderKeepPlus#4]
I have a work and home email. I also have a work and home keep board. Thunderkeep will only let me open one of them (which happens to be my home). I also cannot add an account through the top right menu as this only opens a Firefox screen and accesses keep there. 

Is there any way to have two separate keep accounts open at the same time with Thunderkeep or at least access both?

**Comment by Gara-Dorta** [comment]
Unfortunately Thunderbird uses a common storage for all the websites, so accessing both it's not possible as far as I know. The only work around is to log out from one account and log in on the other one. To log out there is a custom button on Tools -> Google Keep: Sign Out, as shown [here ](https://addons.cdn.mozilla.net/user-media/previews/full/184/184440.png?modified=1494449246).

**Comment by Gara-Dorta** [comment]
Providing a custom click handler as shown here might be the solution to this issue
https://developer.mozilla.org/en-US/docs/Mozilla/Thunderbird/Content_Tabs
