### ISSUE TITLE
Incompatible with Thunderbird 64

### ISSUE THREAD

**Issue by bich30** [Garoe/ThunderKeepPlus#6]
Incompatible with Thunderbird 64

**Comment by Gara-Dorta** [comment]
Thanks for your interest in the addon and for reporting the issue. A new version has been released that supports Tb 64. It's been submitted for review, but if you'd like to install it now, it is available [here](https://github.com/Garoe/ThunderKeepPlus/releases/tag/v0.10.2).
Please let me know if you have any problems with it.

As a note to myself there seems to be radical changes coming to the addon API, see this [link](https://wiki.mozilla.org/Thunderbird/Add-ons_Guide_63).

**Comment by bich30** [comment]
Perfect!!
It's work
Thx!!!
