### ISSUE TITLE
[Future request] Possibility to replace GoogleKeep with different website

### ISSUE THREAD

**Issue by kanlukasz** [Garoe/ThunderKeepPlus#9]
Hello
Is it possible to replace Keep with different website (eg. Trello)?

**Comment by Gara-Dorta** [comment]
It is, the website https://github.com/Garoe/ThunderKeepPlus/blob/master/content/overlay.js#L98 is hard-coded in this line, so it's quite easy to edit. I'll think about adding an option so that it can be changed from the UI in thunderbird.

**Comment by kanlukasz** [comment]
Great, it works.

I think it will be good idea if you add this option to UI.

Or maybe you can release another second version, something like `ThunderTabPlus`, where user could set the address :-) 

Anyway, I leave this ticket open as `Future request`.
If you consider it appropriate to introduce this change, you will close it after new release

Thank for your help

**Comment by Gara-Dorta** [comment]
Minor update, with the rewrite needed for TB 78 the url is now in a new file, see links below. I'm keeping this issue open but I don't think it'll ever be fix unless someone else does writes the code and does a pull request.

https://github.com/Garoe/ThunderKeepPlus/blob/5af9b6daa8fbbe2f5c428851f839446d17bdcb08/src/background.js#L21
https://github.com/Garoe/ThunderKeepPlus/blob/5af9b6daa8fbbe2f5c428851f839446d17bdcb08/src/background.js#L24

**Comment by kanlukasz** [comment]
Thanks for the update. After a while I came to the conclusion that if the add-on is "ThunderKeepPlus" and not "ThunderSOMETHINGPlus", then we should keep to strict direction.

I find that my request looks more like a need to create a new add-on that specializes in delivering this feature (and only this feature)

In addition, I found another addon that probably has the better purpose for it - https://addons.thunderbird.net/pl/thunderbird/addon/browseintab/

Therefore, I think it is better to close this issue as it creates some "go away" in relation to the needs of this repository

Thanks for your time

**Comment by Gara-Dorta** [comment]
Nice one! I had missed the browseintab addon. I had seen another addon that did the same but that was abandoned, so I thought  there were no alternative options. Thanks for sharing and closing the issue.
